name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main  # Or use "master" if that's your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.1' # Replace with your desired Flutter version

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --release
      
      # - name: Fix base href for GitHub Pages subpath
      #   run: sed -i 's|<base href="/">|<base href="/Pool_Mate-Admin/">|' build/web/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          cname: admin.sensorsyncinnovation.com # added Custom Domain so that it don't access github domain
